webtalk_init -webtalk_dir /home/nick/Downloads/embeddedLabs/lab_5/lab_5/lab_5.sim/sim_1/behav/xsim/xsim.dir/controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  4 23:59:25 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "04508fb6-f02a-44eb-9846-832674d11195" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "52f0cd73705548159231663a46418544" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "110" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1720.745 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "265244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 133432012 -regid "" -xml /home/nick/Downloads/embeddedLabs/lab_5/lab_5/lab_5.sim/sim_1/behav/xsim/xsim.dir/controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/nick/Downloads/embeddedLabs/lab_5/lab_5/lab_5.sim/sim_1/behav/xsim/xsim.dir/controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/nick/Downloads/embeddedLabs/lab_5/lab_5/lab_5.sim/sim_1/behav/xsim/xsim.dir/controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
