# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/user/Downloads/embeddedLabs/lab_5/zybo_lab_5.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controls_0_0/design_1_controls_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_controls_0_0 || ORIG_REF_NAME==design_1_controls_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_framebuffer_0_0/design_1_framebuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_framebuffer_0_0 || ORIG_REF_NAME==design_1_framebuffer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_myALU_0_0/design_1_myALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_myALU_0_0 || ORIG_REF_NAME==design_1_myALU_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pixel_pusher_0_0/design_1_pixel_pusher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pixel_pusher_0_0 || ORIG_REF_NAME==design_1_pixel_pusher_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_regs_0_0/design_1_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_regs_0_0 || ORIG_REF_NAME==design_1_regs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_div_25_0_0/design_1_clock_div_25_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_div_25_0_0 || ORIG_REF_NAME==design_1_clock_div_25_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_div_112500_0_0/design_1_clock_div_112500_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_div_112500_0_0 || ORIG_REF_NAME==design_1_clock_div_112500_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vga_ctrl_0_0/design_1_vga_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vga_ctrl_0_0 || ORIG_REF_NAME==design_1_vga_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_0_0/design_1_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_0_0 || ORIG_REF_NAME==design_1_uart_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_blk_mem_gen_0_2} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
